name: 'Giphy PR comment'
description: 'Greet someone and record the time'
inputs:
  github-token:  # id of input
    description: 'PAT token'
    required: true
  giphy-api-key:
    description: 'PAT token'
    required: true    
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.giphy-api-key }}